/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminiRouteImport } from './routes/termini'
import { Route as RegaloRouteImport } from './routes/regalo'
import { Route as OrdinaRouteImport } from './routes/ordina'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as CarteRouteImport } from './routes/carte'
import { Route as IndexRouteImport } from './routes/index'

const TerminiRoute = TerminiRouteImport.update({
  id: '/termini',
  path: '/termini',
  getParentRoute: () => rootRouteImport,
} as any)
const RegaloRoute = RegaloRouteImport.update({
  id: '/regalo',
  path: '/regalo',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdinaRoute = OrdinaRouteImport.update({
  id: '/ordina',
  path: '/ordina',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteRoute = CarteRouteImport.update({
  id: '/carte',
  path: '/carte',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carte': typeof CarteRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/ordina': typeof OrdinaRoute
  '/regalo': typeof RegaloRoute
  '/termini': typeof TerminiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carte': typeof CarteRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/ordina': typeof OrdinaRoute
  '/regalo': typeof RegaloRoute
  '/termini': typeof TerminiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carte': typeof CarteRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/ordina': typeof OrdinaRoute
  '/regalo': typeof RegaloRoute
  '/termini': typeof TerminiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/carte' | '/chi-siamo' | '/ordina' | '/regalo' | '/termini'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carte' | '/chi-siamo' | '/ordina' | '/regalo' | '/termini'
  id:
    | '__root__'
    | '/'
    | '/carte'
    | '/chi-siamo'
    | '/ordina'
    | '/regalo'
    | '/termini'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarteRoute: typeof CarteRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  OrdinaRoute: typeof OrdinaRoute
  RegaloRoute: typeof RegaloRoute
  TerminiRoute: typeof TerminiRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termini': {
      id: '/termini'
      path: '/termini'
      fullPath: '/termini'
      preLoaderRoute: typeof TerminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regalo': {
      id: '/regalo'
      path: '/regalo'
      fullPath: '/regalo'
      preLoaderRoute: typeof RegaloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordina': {
      id: '/ordina'
      path: '/ordina'
      fullPath: '/ordina'
      preLoaderRoute: typeof OrdinaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carte': {
      id: '/carte'
      path: '/carte'
      fullPath: '/carte'
      preLoaderRoute: typeof CarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarteRoute: CarteRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  OrdinaRoute: OrdinaRoute,
  RegaloRoute: RegaloRoute,
  TerminiRoute: TerminiRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
